# Generated by Django 6.0.2 on 2026-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora de Término')),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID no Google Calendar')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
