# Generated by Django 6.0.2 on 2026-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('horario', models.CharField(max_length=100, verbose_name='Horário (ex: 19:00 às 21:00)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem no Dia')),
            ],
            options={
                'verbose_name': 'Programação Semanal',
                'verbose_name_plural': 'Programações Semanais',
                'ordering': ['dia_semana', 'ordem'],
            },
        ),
    ]
