# Generated by Django 6.0.2 on 2026-03-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_migracao_funcao_dinamica'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
