# Generated by Django 6.0.2 on 2026-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_membro_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.CharField(default='0', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
