# Generated by Django 6.0.2 on 2026-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0006_configuracaoportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_chave', models.CharField(default='adcapital.church@gmail.com', max_length=255, verbose_name='Chave PIX')),
                ('banco_nome', models.CharField(default='BANCO DO BRASIL', max_length=100, verbose_name='Nome do Banco')),
                ('beneficiario', models.CharField(default='IGREJA EVANGELICA ASSEMBLEIA DE DEUS MINISTERIO NA CAPITAL', max_length=255, verbose_name='Beneficiário')),
                ('instagram_url', models.URLField(default='https://instagram.com/adcapital.igreja', verbose_name='Instagram')),
                ('youtube_url', models.URLField(default='https://www.youtube.com/@adcapital.church313', verbose_name='YouTube')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('video_sobre_nos_url', models.URLField(blank=True, null=True, verbose_name='Vídeo Sobre Nós (YouTube URL)')),
                ('endereco_completo', models.TextField(default='Ch 18 Lt 6/7 Setor de Mansões IAPI - Guará 2 - Brasília - DF - 71.081-245', verbose_name='Endereço Completo')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='URL do Google Maps')),
                ('pastor_nome', models.CharField(default='Pastor Responsável', max_length=255, verbose_name='Nome do Pastor')),
                ('pastoral_titulo', models.CharField(default='Uma Palavra de Fé', max_length=255, verbose_name='Título da Mensagem')),
                ('pastoral_texto', models.TextField(blank=True, verbose_name='Texto da Palavra Pastoral')),
                ('pastor_foto', models.ImageField(blank=True, null=True, upload_to='site/pastor/', verbose_name='Foto do Pastor')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='site/galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
