# Generated by Django 6.0.2 on 2026-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_configuracaosite_fotogaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], default='SOLTEIRO', max_length=20),
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros/fotos/'),
        ),
        migrations.AddField(
            model_name='membro',
            name='motivo_entrada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='motivo_saida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Nascimento'),
        ),
        migrations.AddField(
            model_name='membro',
            name='unidade',
            field=models.CharField(default='Sede', max_length=100),
        ),
        migrations.AlterField(
            model_name='membro',
            name='genero',
            field=models.CharField(choices=[('VARAO', 'Varão'), ('VAROA', 'Varoa')], default='VARAO', max_length=10),
        ),
    ]
