# Generated by Django 6.0.2 on 2026-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_membro_estado_civil_membro_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='lgpd_consentido',
            field=models.BooleanField(default=False, verbose_name='Termo LGPD Assinado'),
        ),
        migrations.AddField(
            model_name='membro',
            name='lgpd_data_aceite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite LGPD'),
        ),
        migrations.AddField(
            model_name='membro',
            name='lgpd_documento',
            field=models.FileField(blank=True, null=True, upload_to='membros/lgpd/', verbose_name='Documento LGPD Assinado'),
        ),
    ]
