# Generated by Django 6.0.2 on 2026-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0009_membro_lgpd_consentido_membro_lgpd_data_aceite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
